### ISSUE TITLE
Make 3D axes run alongside origin (0,0,0)

### ISSUE THREAD

**Issue by hatten33** [yannrichet/jmathplot#13]
Is it possible for all the axes to intersect 0,0,0 so it is easier to see which values are above/below the origin? I've already tried axis.setOrigin() to no avail.

**Comment by yannrichet** [comment]
No, sorry. The axes are designed in a "box" mode, so it is not possible with this design. 
But you can also add black lines with addLinePlot, using getOrigin coordinates to match the limit of the box (and just set X,Y or Z set to 0).
