### ISSUE TITLE
Maven dependencies are the wrong case

### ISSUE THREAD

**Issue by mrami4** [yannrichet/jmathplot#15]
The Linux version of Maven, at least, is case sensitive, so where the pom currently has

	<dependencies>
		<dependency>
			<groupId>com.github.yannrichet</groupId>
			<artifactId>jmathio</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.yannrichet</groupId>
			<artifactId>jmatharray</artifactId>
			<version>1.0</version>
		</dependency>
	</dependencies>

it should instead have

	<dependencies>
		<dependency>
			<groupId>com.github.yannrichet</groupId>
			<artifactId>JMathIO</artifactId>
			<version>1.0</version>
		</dependency>
		<dependency>
			<groupId>com.github.yannrichet</groupId>
			<artifactId>JMathArray</artifactId>
			<version>1.0</version>
		</dependency>
	</dependencies>

**Comment by yannrichet** [comment]
fixed. thanks.
