### ISSUE TITLE
Update Maven artifactId in README

### ISSUE THREAD

**Issue by dreamworld** [yannrichet/jmathplot#18]
The dependency item in the README.md file will cause a maven error

 > Could not find artifact com.github.yannrichet:jmathplot:jar:1.0 in central (https://repo.maven.apache.org/maven2)

```xml
<dependencies>
...
    <dependency>
      <groupId>com.github.yannrichet</groupId>
      <artifactId>jmathplot</artifactId>
      <version>1.0</version>
    </dependency>
...
</dependencies>
```
Please update the artifactId to  `<artifactId>JMathPlot</artifactId>`, `version>1.0.1</version>` to avoid such error.

**Comment by lcoulet** [comment]
Thanks, this issue helped me to solve the problem. That would be nice to fix the documentation accordingly.
