### ISSUE TITLE
Does jmathplot support svg export?

### ISSUE THREAD

**Issue by stefaneidelloth** [yannrichet/jmathplot#22]
Does jmathplot support svg export? If not... is it planned for the future?

**Comment by yannrichet** [comment]
Not for now. But I expect it needs few changes in the following lines:
https://github.com/yannrichet/jmathplot/search?utf8=%E2%9C%93&q=ImageIO&type=Code
You should also use batik as a SVG engine: 
http://xmlgraphics.apache.org/batik/using/svg-generator.html

Best
