### ISSUE TITLE
Handle (hide/skip) NaN values

### ISSUE THREAD

**Issue by adufour** [yannrichet/jmathplot#30]
I have this profile I'm plotting (line plot), and some of the values are (deliberately) set to NaN (in places where no data is available). Would it be possible to just "skip" these values, instead of treating them as 0 (NB: I think that's what's happening, but I could be wrong on the precise behaviour). In essence, I'd like to see the line plot with just a gap wherever the NaN(s) occur.

Thanks and kudos for the great library!

**Comment by yannrichet** [comment]
Checkout last revision. Should be ok.
