### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by ridasardaar** [yannrichet/jmathplot#36]
I am using Moea framwork and want to concatenate my file for this i am using following code.
package knapsackthesisconcatefiles;

import java.io.*;

public class ConcatenatedFiles {

        static public void main(String arg[]) throws java.io.IOException {
        	    //String folderName = "PROBLEM_AGENT400_TASK100";
        	    //String folderName = "scalability-400agents";
        	    String folderName = "no of items";
        	    PrintWriter pw = new PrintWriter(new FileOutputStream("C:/Users/l155089/Desktop/knapsack project/MOEAFramework-2.11/MOEAFramework-2.11/test1/items-ALL-NONDOMINATED-COMBINED.txt"));
                File file = new File("C:/Users/l155089/Desktop/knapsack project/MOEAFramework-2.11/MOEAFramework-2.11 /test1/"+folderName+"/");
                File[] files = file.listFiles();
              
                
                System.out.println("Processing 1 ");
                for (int i = 0; i < files.length; i++) {
                	
                	  System.out.println("Processing 1 ");
                	
                	File[] subFiles =null;
                	File[] tempSubFiles =null;
                	if(files[i].isDirectory()) {
                		tempSubFiles = files[i].listFiles();
                		if(tempSubFiles[0].isDirectory()) 
                			subFiles = tempSubFiles[0].listFiles();  //if only 1 nested folder
                		else
                			subFiles = tempSubFiles;
                		
                	}
                	if (subFiles==null) continue;
                	for (int j = 0; j < subFiles.length; j++) {
                		if(!subFiles[j].getName().startsWith("FUN")) 
                			continue;
                        System.out.println("Processing j "+j + subFiles[j].getPath() + "... ");
                        BufferedReader br = new BufferedReader(new FileReader(subFiles[j]
                                        .getPath()));
                        String line = br.readLine();
                        while (line != null) {
                                pw.println(line);
                                line = br.readLine();
                        }
                        br.close();
                	}
                	  System.out.println("Processing 2 ");

                }
                pw.close();
                System.out.println("All files have been concatenated into ALL-NONDOMINATED-COMBINED.txt");
        }
}

Exception in thread "main" java.lang.NullPointerException
	at knapsackthesisconcatefiles.ConcatenatedFiles.main(ConcatenatedFiles.java:19)

this throw a null pointer exception. kindly help me.

**Comment by yannrichet** [comment]
?
